#!/bin/bash

# Copyright Kieran Whitbread 2010
# This file is released under the following license: 
# http://opensource.org/licenses/lgpl-2.1.php GNU Lesser General Public License


DEFAULT_INTERVAL=60
DEV_ID_MAJOR=$(grep "device-mapper" /proc/devices | cut -d\  -f 1)
PID_FILE=
STAT_FILE=/var/lib/iostat-poller/stats
TMP_FILE="/tmp/$(basename "$0").$$"

# call this with a partition device name as the argument (e.g. hda1, dm-4, sdb2)
# converts device name for Device Mapper devices to their friendly name
# calling iostats -N only sets the device mapper name if device-mapper major id is 253
# (check in /proc/devices)
function _device_map() {
        DEV_ID_MINOR="${1##dm-}"
        if [ "$1" = "$DEV_ID_MINOR" ]
        then
                # Not a device mapper name, so just echo it back and exit
                echo "$1"
                return
        fi
        echo $(ls -lQ "/dev/mapper" | egrep "^b.*${DEV_ID_MAJOR}, +${DEV_ID_MINOR}" | sed -e 's/^[^"]*"\(.*\)"$/\1/')
}
function _trap() {
        if [ "$PID_FILE" ]
        then
                rm "$PID_FILE" 2>&1 > /dev/null
        fi
        rm -f "${TMP_FILE}" 2>&1 > /dev/null
        exit
}


trap _trap TERM INT HUP EXIT KILL

if [ ! -w "$STAT_FILE" ]
then
        echo "Cannot write to $STAT_FILE" 1>&2
        exit 1
fi

case "$1" in
        --pidfile=*)
                PID_FILE="${1#--pidfile=}"
                shift
                echo $$ > "$PID_FILE"
        ;;
        [0-9])
                INTERVAL=$1
        ;;
esac

touch "$TMP_FILE"

exec <&-
exec 2> /dev/null
exec > /dev/null

if [ -z "$INTERVAL" ]
then
        INTERVAL=$DEFAULT_INTERVAL
fi

iostat -dmx $INTERVAL | while read LINE
do
        if [ "${LINE:0:8}" = "Device: " ]
        then
                continue
        fi
        if [ "$LINE" ]
        then
                DEV=$(echo "${LINE}" | cut -d\  -f 1)
                DEV_NAME=$(_device_map "${DEV}")
                LINE=$(echo "${LINE}" | sed -e "s/^${DEV} /${DEV_NAME} /")
                STATS="${STATS}\n${LINE}"
        else
                # iostat out put for each device can span more than one line.
                echo -e "${STATS}" | sed -e 'N;s/\(^[^ ]*\)\(\n\)\(.*\)$/\1\3/'  | sed -e 's/  */ /g' > "${TMP_FILE}"
                STATS=
                mv "${TMP_FILE}" "${STAT_FILE}"
		sed -i 's/,/\./g' "${STAT_FILE}"
        fi
done
